# Generated by Django 6.1 on 2026-08-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='household_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='income_level',
            field=models.CharField(blank=True, choices=[('under-25000', 'Under $25,000 per year'), ('25000-49999', '$25,000-$49,999'), ('50000-74999', '$50,000-$74,999'), ('75000-plus', '$75,000 or more')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='max_distance_km',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_category',
            field=models.CharField(blank=True, choices=[('bakery', 'Bakery'), ('groceries', 'Groceries'), ('meals', 'Meals'), ('snacks', 'Snacks')], max_length=20),
        ),
    ]
