# Generated by Django 6.1 on 2026-08-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_household_size_user_income_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_food_access',
            field=models.CharField(blank=True, choices=[('reliable', 'Reliable access'), ('sometimes-limited', 'Sometimes limited'), ('often-limited', 'Often limited'), ('very-limited', 'Very limited')], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dependents',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed-full-time', 'Employed full-time'), ('employed-part-time', 'Employed part-time'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('unable-to-work', 'Unable to work')], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='housing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_allocations_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
