# Generated by Django 5.0.7 on 2026-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_needy_metric"),
        (
            "accounts",
            "0003_user_current_food_access_user_debt_user_dependents_and_more",
        ),
    ]

    operations = []
