# Generated by Django 5.0.7 on 2026-08-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_20260829_0656"),
        ("accounts", "0004_merge_20260829_0702"),
    ]

    operations = []
