# Generated by Django 5.0.7 on 2026-08-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergens_to_avoid', models.JSONField(blank=True, default=list)),
                ('dietary_styles', models.JSONField(blank=True, default=list)),
                ('meal_goal', models.CharField(blank=True, max_length=30)),
                ('max_distance_km', models.PositiveSmallIntegerField(default=5)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('responses', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nutrition.foodpreferenceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('ingredients', models.JSONField(default=list)),
                ('allergens', models.JSONField(default=list)),
                ('possible_cross_contact', models.JSONField(blank=True, default=list)),
                ('nutrition', models.JSONField(blank=True, default=dict)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('model_version', models.CharField(default='preferences-v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='nutrition.foodpreferenceprofile')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='nutrition.restaurantmeal')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchrecommendation',
            constraint=models.UniqueConstraint(fields=('profile', 'meal', 'model_version'), name='unique_profile_meal_model_match'),
        ),
    ]
