import { AlertTriangle, Check, MapPin, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const meals = [
  { id: 1, name: 'Grilled chicken harvest bowl', restaurant: 'The Local Table', image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=85', score: 94, price: '$4.00', reasons: ['High protein', 'Within your sodium preference', 'No declared allergens'], warning: '' },
  { id: 2, name: 'Lentil and roast vegetable bowl', restaurant: 'Green Corner Kitchen', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=85', score: 89, price: 'Free', reasons: ['Plant-based', 'High fibre', 'Matches your preferences'], warning: 'May contain sesame through cross-contact' },
  { id: 3, name: 'Salmon rice plate', restaurant: 'Marrickville Pantry', image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=85', score: 82, price: '$3.50', reasons: ['Source of omega-3', 'Balanced meal'], warning: 'Nutrition values supplied by restaurant' },
];

export default function NutritionMatchesPage() {
  return <main className="match-page"><header className="health-header"><Link className="logo" to="/"><img src="/savr-icon.png" alt=""/><span>SAVR</span></Link><nav><Link to="/health-profile">Edit preferences</Link><Link to="/requests">My requests</Link></nav></header><div className="match-shell"><header className="match-intro"><div><p className="eyebrow">Suggested for you</p><h1>Meals you might like</h1><p>Ordered using the optional preferences you shared, plus distance and availability.</p></div><div className="match-safety"><ShieldCheck/><span><strong>Allergy filter active</strong>Meals with your selected declared allergens are hidden.</span></div></header><aside className="clinical-disclaimer"><AlertTriangle size={18}/><p>Suggestions are general information, not medical advice. Always confirm ingredients with the restaurant if you have an allergy.</p></aside><section className="meal-match-grid" aria-label="Suggested meals">{meals.map((meal) => <article className="meal-match" key={meal.id}><div className="meal-match__image"><img src={meal.image} alt=""/><span>{meal.score}% fit</span></div><div className="meal-match__body"><small>{meal.restaurant}</small><h2>{meal.name}</h2><ul>{meal.reasons.map((reason) => <li key={reason}><Check size={14}/>{reason}</li>)}</ul>{meal.warning && <p className="meal-warning"><AlertTriangle size={14}/>{meal.warning}</p>}<div className="meal-match__footer"><span><MapPin size={14}/>1.2 km</span><strong>{meal.price}</strong></div><button className="button button--wide">View meal</button></div></article>)}</section><p className="match-method">Why these results? Allergen selections are checked first. Remaining meals are ordered using your food preferences, distance, value and availability. You can edit or clear your preferences at any time.</p></div></main>;
}
