import { AlertTriangle, Check, MapPin, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const meals = [
  { id: 1, name: 'Grilled chicken harvest bowl', restaurant: 'The Local Table', image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=85', fit: 'Great fit', price: '$4.00', reasons: ['Filling option', 'Nearby', 'No selected ingredients'], warning: '' },
  { id: 2, name: 'Lentil and roast vegetable bowl', restaurant: 'Green Corner Kitchen', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=85', fit: 'Good fit', price: 'Free', reasons: ['Plant-based', 'Good value', 'Matches your preferences'], warning: 'Restaurant notes possible sesame cross-contact' },
  { id: 3, name: 'Salmon rice plate', restaurant: 'Marrickville Pantry', image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=85', fit: 'Worth a look', price: '$3.50', reasons: ['Balanced option', 'Available today'], warning: '' },
];

export default function NutritionMatchesPage() {
  return <main className="match-page"><header className="health-header"><Link className="logo" to="/"><img src="/savr-icon.png" alt=""/><span>SAVR</span></Link><nav><Link to="/preferences">Edit</Link><Link to="/requests">My requests</Link></nav></header><div className="match-shell"><header className="match-intro"><div><p className="eyebrow">Suggested</p><h1>Food you might like</h1><p>Based on your optional preferences, distance and availability.</p></div><div className="match-safety"><ShieldCheck/><span><strong>Avoid list on</strong>Selected ingredients are filtered first.</span></div></header><aside className="clinical-disclaimer"><AlertTriangle size={18}/><p>Always confirm ingredients with the restaurant if you have an allergy.</p></aside><section className="meal-match-grid" aria-label="Suggested meals">{meals.map((meal) => <article className="meal-match" key={meal.id}><div className="meal-match__image"><img src={meal.image} alt=""/><span>{meal.fit}</span></div><div className="meal-match__body"><small>{meal.restaurant}</small><h2>{meal.name}</h2><ul>{meal.reasons.map((reason) => <li key={reason}><Check size={14}/>{reason}</li>)}</ul>{meal.warning && <p className="meal-warning"><AlertTriangle size={14}/>{meal.warning}</p>}<div className="meal-match__footer"><span><MapPin size={14}/>1.2 km</span><strong>{meal.price}</strong></div><button className="button button--wide">View meal</button></div></article>)}</section><p className="match-method">Selected ingredients are checked first. Other meals are ordered by preference, distance, value and availability.</p></div></main>;
}
