import { AlertTriangle, Check, MapPin, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { listings } from '../../data/listings';
import { loadPreferences, suggestListings } from '../../lib/foodPreferences';

export default function NutritionMatchesPage() {
  const preferences = loadPreferences();
  const { matches, excluded } = suggestListings(listings, preferences);

  return <main className="match-page"><header className="health-header"><Link className="logo" to="/"><img src="/savr-icon.png" alt=""/><span>SAVR</span></Link><nav><Link to="/preferences">Edit</Link><Link to="/requests">My requests</Link></nav></header><div className="match-shell"><header className="match-intro"><div><p className="eyebrow">Suggested</p><h1>Food you might like</h1><p>Based only on the optional preferences, budget and distance you chose.</p></div><div className="match-safety"><ShieldCheck/><span><strong>Avoid list on</strong>{excluded} unavailable or unsuitable {excluded === 1 ? 'option was' : 'options were'} hidden.</span></div></header><aside className="clinical-disclaimer"><AlertTriangle size={18}/><p>Suggestions are not medical advice. Always confirm ingredients and cross-contact with the business if you have an allergy.</p></aside>{matches.length ? <section className="meal-match-grid" aria-label="Suggested food">{matches.map(({ listing, fit, reasons, warnings }) => <article className="meal-match" key={listing.id}><div className="meal-match__image"><img src={listing.image} alt=""/><span>{fit}</span></div><div className="meal-match__body"><small>{listing.vendor}</small><h2>{listing.name}</h2><ul>{reasons.map((reason) => <li key={reason}><Check size={14}/>{reason}</li>)}</ul>{warnings.map((warning) => <p className="meal-warning" key={warning}><AlertTriangle size={14}/>{warning}. Confirm before requesting.</p>)}<div className="meal-match__footer"><span><MapPin size={14}/>{listing.distance}</span><strong>{listing.price}</strong></div><Link className="button button--wide" to={`/marketplace/${listing.slug}`}>View food</Link></div></article>)}</section> : <section className="empty-state"><h2>No suitable food is available right now</h2><p>Try increasing your distance or price, or check back when new food is listed.</p><Link className="button" to="/preferences">Edit preferences</Link></section>}<p className="match-method">Declared allergens, distance and budget are checked first. Remaining food is ordered by your preferences, distance and value. No medical records are required.</p></div></main>;
}
