import { DashboardShell, MetricCard, StatusBadge, type DashboardNavItem } from "../../components/dashboard/DashboardShell";

const nav: DashboardNavItem[] = [
  { label: "Overview", icon: "▦", href: "/admin", active: true }, { label: "Users", icon: "♙", href: "/admin/users" }, { label: "Vendors", icon: "▣", href: "/admin/vendors" }, { label: "Listings", icon: "□", href: "/admin/listings" }, { label: "Requests", icon: "♡", href: "/admin/requests" }, { label: "Allocations", icon: "◇", href: "/admin/allocations" }, { label: "Reports", icon: "⚑", href: "/admin/reports" }, { label: "Settings", icon: "⚙", href: "/admin/settings" }, { label: "Logs", icon: "≡", href: "/admin/logs" },
];
const categories = ["Bakery 32%", "Groceries 26%", "Meals 20%", "Produce 14%", "Other 8%"];

export default function AdminDashboard() {
  return <DashboardShell productLabel="Admin" navItems={nav} userName="Admin" userRole="Super user">
    <header className="dashboard-heading"><div><h1>Platform overview <small>(Today)</small></h1><p>Marketplace activity, fairness, impact and operational health.</p></div><div className="heading-actions"><button className="button button--quiet">May 10-16, 2024</button><button className="button button--quiet">Export ⌄</button></div></header>
    <section className="metric-grid metric-grid--admin" aria-label="Platform totals"><MetricCard label="Total users" value="12,540" detail="+6% yesterday"/><MetricCard label="Verified vendors" value="1,285" detail="+4%"/><MetricCard label="Listings today" value="342" detail="+12%"/><MetricCard label="Meals allocated" value="4,612" detail="+10%"/><MetricCard label="Food rescued" value="2,860 kg" detail="+8%"/></section>
    <div className="admin-chart-grid">
      <section className="dashboard-panel"><div className="panel-heading"><h2>Need score distribution</h2><a href="/admin/users">View users</a></div><div className="donut-chart donut-chart--need" role="img" aria-label="Need distribution: very high 38%, high 29%, medium 21%, low 12%"><span>12,540<small>Total users</small></span></div><ul className="chart-legend"><li>Very high (80+) <strong>38%</strong></li><li>High (60-79) <strong>29%</strong></li><li>Medium (40-59) <strong>21%</strong></li><li>Low (&lt;40) <strong>12%</strong></li></ul></section>
      <section className="dashboard-panel fairness-panel"><div className="panel-heading"><h2>Allocation fairness</h2></div><div className="donut-chart donut-chart--fairness" role="img" aria-label="Fairness score 92 out of 100"><span>92<small>/100</small></span></div><StatusBadge>Excellent</StatusBadge><p>Based on need, distance, dietary match and allocation history.</p></section>
      <section className="dashboard-panel"><div className="panel-heading"><h2>Vendor activity <small>(last 7 days)</small></h2><a href="/admin/vendors">View details</a></div><div className="bar-chart" role="img" aria-label="Vendor activity trending upward over seven days">{[32,46,63,72,80,76,58].map((height, index) => <span key={index} className={`bar bar--${height}`}><i>{height}</i></span>)}</div></section>
      <section className="dashboard-panel"><div className="panel-heading"><h2>Top food categories</h2></div><div className="donut-chart donut-chart--categories" role="img" aria-label={categories.join(", ")}><span>342<small>Listings</small></span></div><ul className="chart-legend">{categories.map((category) => <li key={category}>{category}</li>)}</ul></section>
    </div>
    <div className="admin-operations-grid"><section className="dashboard-panel"><div className="panel-heading"><h2>Manual review queue (24)</h2><a href="/admin/reports">View queue</a></div><article className="alert-row"><span>⚑</span><div><strong>Vendor verification</strong><p>8 accounts awaiting documents</p></div><StatusBadge tone="warning">Review</StatusBadge></article><article className="alert-row"><span>!</span><div><strong>Listing reports</strong><p>6 reports require attention</p></div><StatusBadge tone="danger">Urgent</StatusBadge></article></section><section className="dashboard-panel"><div className="panel-heading"><h2>Recent system alerts</h2><a href="/admin/logs">View logs</a></div><StatusBadge>All systems operational</StatusBadge><ul className="system-list"><li>Matching engine healthy</li><li>Payments processing normally</li><li>Data backups complete</li></ul></section></div>
  </DashboardShell>;
}
